#!/bin/bash

CONFIG_PATH=/etc/ssl_expire
CONFIG_FILE=ssl_expire.conf
source "$CONFIG_PATH"/"$CONFIG_FILE"

while [ : ]
do
    for site in ${$Websites[@]}; do
        data=$(ssl_expire --ip "$site")
        zabbix_sender -z "$ZabbixServer" -s "$Hostname" -k "$Key" -o "$data"
        sleep 1
    done
done